
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: 10

        ScrollView:
            do_scroll_x: True

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10

                Button:
                    text: 'Activity 1'
                    size_hint_y: None
                    height: '48dp'

